name: Run Tests and Enforce Merge Rules

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java JDK 11
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install dependencies using Maven
      - name: Install dependencies
        run: mvn install -DskipTests

      # Run tests
      - name: Run tests
        run: mvn test

      # Upload test results (optional but helpful)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/test-classes
