name: Run Tests and Enforce Merge Rules

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use a Linux-based runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '23'  # Set the Java version (OpenJDK 23)
        distribution: 'zulu'  # Use the Zulu OpenJDK distribution

    - name: Install MySQL client
      run: sudo apt-get install mysql-client  # Install MySQL client for connecting to the database

    - name: Set up MySQL database
      run: |
        mysql -h mysql-1e7edf9b-lhr-b3a4.e.aivencloud.com -u avnadmin -pAVNS_BOwgsttXw1DG074BVy8 -e "CREATE DATABASE IF NOT EXISTS softwaretesting;"
      env:
        MYSQL_PWD: AVNS_BOwgsttXw1DG074BVy8

    - name: Run tests
      run: |
        # Compile and run tests using Maven
        # If you're not using Maven or Gradle, just compile the classes with javac or use any build tool you prefer
        javac -cp ".:/path/to/junit-5.8.1.jar:/path/to/mysql-connector-java-9.0.0.jar" src/test/*.java  # Compile test cases
        java -cp ".:/path/to/junit-5.8.1.jar:/path/to/mysql-connector-java-9.0.0.jar" org.junit.platform.console.ConsoleLauncher --scan-classpath  # Run tests
