name: Run Tests and Enforce Merge Rules

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use OpenJDK from Eclipse Temurin
          java-version: '23.0.1' # Use the version you specified

      # Cache dependencies (optional, useful for large projects)
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Set up environment variables for classpath
      - name: Set environment variables
        run: |
          echo "CLASSPATH=.:$PWD/lib/junit-jupiter-api-5.8.1.jar:$PWD/lib/junit-platform-console-standalone-1.8.1.jar" >> $GITHUB_ENV
          echo "OUTPUT_DIR=$PWD/out" >> $GITHUB_ENV

      # Create output directory
      - name: Create output directory
        run: mkdir -p $OUTPUT_DIR

      # Compile the code
      - name: Compile Java files
        run: |
          javac -cp "$CLASSPATH" -d "$OUTPUT_DIR" src/loginapp/LoginApp.java src/test/LoginTest.java

      # Run tests
      - name: Run JUnit tests
        run: |
          java -cp "$CLASSPATH:$OUTPUT_DIR" org.junit.platform.console.ConsoleLauncher --scan-classpath
