name: Run Tests and Enforce Merge Rules

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Run tests using Maven
      - name: Run tests
        run: mvn test
